In [1]:

from pathlib import Path
import pandas as pd

# مكان ملفات التاسك
DATA_DIR = Path.cwd()

# عرض الملفات الموجودة في الفولدر
for file in sorted(DATA_DIR.iterdir()):
    if file.is_file():
        print(file.name)

01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls
02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls
03_نسبة_الالتحاق_بالتعليم_الثانوي.xls
country_dictionary_v1.csv
economy_education_cleaning.ipynb

In [3]:

%pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.2
[notice] To update, run: C:\Users\compu_tech\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:

# البحث عن ملفات Excel وCSV
excel_files = sorted(DATA_DIR.glob("*.xls"))
csv_files = sorted(DATA_DIR.glob("*.csv"))

print("Excel files:", len(excel_files))
print("CSV files:", len(csv_files))

# نتأكد إن الملفات المطلوبة موجودة
if len(excel_files) != 3:
    raise ValueError(
        f"Expected 3 Excel files, but found {len(excel_files)}"
    )

if len(csv_files) != 1:
    raise ValueError(
        f"Expected 1 CSV file, but found {len(csv_files)}"
    )

# قراءة ملفات Excel بدون تعديل الملفات الأصلية
raw_data = {}

for file in excel_files:
    raw_data[file.name] = pd.read_excel(file, engine="xlrd")
    print(f"\nFile: {file.name}")
    print("Shape:", raw_data[file.name].shape)
    print("Columns:")
    print(raw_data[file.name].columns.tolist())
    display(raw_data[file.name].head(3))

# قراءة Country Dictionary
dictionary = pd.read_csv(csv_files[0])

print("\nCountry Dictionary:", csv_files[0].name)
print("Shape:", dictionary.shape)
print("Columns:", dictionary.columns.tolist())
display(dictionary.head(5))

Excel files: 3
CSV files: 1

File: 01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls
Shape: (268, 70)
Columns:
['Data Source', 'World Development Indicators', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0

File: 02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls
Shape: (268, 70)
Columns:
['Data Source', 'World Development Indicators', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0

File: 03_نسبة_الالتحاق_بالتعليم_الثانوي.xls
Shape: (268, 70)
Columns:
['Data Source', 'World Development Indicators', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Last Updated Date,2026-07-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0

Country Dictionary: country_dictionary_v1.csv
Shape: (196, 13)
Columns: ['ISO3', 'M49', 'Country', 'WB_Name', 'WHO_Name', 'GHED_Name', 'Nurses_Source_Name', 'Region', 'Income_Group', 'In_GHED', 'In_WHO_Doctors', 'In_WorldBank', 'In_Nurses_Source']

,ISO3,M49,Country,WB_Name,WHO_Name,GHED_Name,Nurses_Source_Name,Region,Income_Group,In_GHED,In_WHO_Doctors,In_WorldBank,In_Nurses_Source
0,AFG,4,Afghanistan,Afghanistan,Afghanistan,Afghanistan,Afghanistan,EMR,Low,True,True,True,True
1,AGO,24,Angola,Angola,Angola,Angola,Angola,AFR,Lower-middle,True,True,True,True
2,ALB,8,Albania,Albania,Albania,Albania,Albania,EUR,Upper-middle,True,True,True,True
3,AND,20,Andorra,Andorra,Andorra,Andorra,Andorra,EUR,High,True,True,True,True
4,ARE,784,United Arab Emirates,United Arab Emirates,United Arab Emirates,United Arab Emirates,United Arab Emirates,EMR,High,True,True,True,True

In [5]:
    
# إعادة قراءة ملفات World Bank باستخدام الصف الصحيح للعناوين

raw_data = {}

for file in sorted(DATA_DIR.glob("*.xls")):
    df = pd.read_excel(file, header=2, engine="xlrd")
    raw_data[file.name] = df

    print("\n" + "=" * 60)
    print("File:", file.name)
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    display(df.head(3))

============================================================
File: 01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls
Shape: (266, 70)
Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025.000000
1,Aruba,ABW,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,36926.113069,38213.289239,39378.228411,39754.560072,30408.827090,35207.170909,39083.461640,42783.248907,45428.002728,NaN
2,Africa Eastern and Southern,AFE,"GDP per capita, PPP (constant 2021 internation...",NY.GDP.PCAP.PP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4210.935695,4223.188050,4229.839634,4200.531044,3978.133502,4049.969513,4098.126192,4076.224898,4099.889812,4164.679177

============================================================
File: 02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls
Shape: (266, 70)
Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000,2023.000000,2024.000000,2025.0
1,Aruba,ABW,"Literacy rate, adult total (% of people ages 1...",SE.ADT.LITR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Africa Eastern and Southern,AFE,"Literacy rate, adult total (% of people ages 1...",SE.ADT.LITR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,70.959999,70.879997,71.669998,72.800003,72.980003,72.720001,73.059998,73.370003,73.699997,NaN

============================================================
File: 03_نسبة_الالتحاق_بالتعليم_الثانوي.xls
Shape: (266, 70)
Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64', 'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68', 'Unnamed: 69']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69
0,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.00000,2023.000000,2024.000000,2025.0
1,Aruba,ABW,"School enrollment, secondary (% gross)",SE.SEC.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,137.829788,139.320587,135.124725,123.625908,131.80217,NaN,124.379367,NaN
2,Africa Eastern and Southern,AFE,"School enrollment, secondary (% gross)",SE.SEC.ENRR,NaN,NaN,NaN,NaN,NaN,NaN,...,42.681499,43.254089,43.559410,44.128731,44.682560,45.150532,45.28162,45.155392,45.606079,NaN

In [6]:

from pathlib import Path
import pandas as pd

DATA_DIR = Path.cwd()

# قراءة قاموس الدول
dictionary_path = DATA_DIR / "country_dictionary_v1.csv"
dictionary = pd.read_csv(dictionary_path, dtype={"ISO3": "string"})

dictionary["ISO3"] = dictionary["ISO3"].str.strip().str.upper()

print("Dictionary shape:", dictionary.shape)
print("Duplicate ISO3 codes:", dictionary["ISO3"].duplicated().sum())
print("Missing ISO3 codes:", dictionary["ISO3"].isna().sum())

# قراءة ملفات المؤشرات الثلاثة
raw_data = {}

excel_files = sorted(DATA_DIR.glob("*.xls"))

for file in excel_files:
    df = pd.read_excel(file, header=3, engine="xlrd")

    # تنظيف أسماء الأعمدة والمسافات في الأكواد
    df.columns = [str(col).strip() for col in df.columns]

    if "Country Code" not in df.columns:
        raise ValueError(
            f"Country Code column not found in {file.name}. "
            f"Columns: {df.columns.tolist()}"
        )

    df["Country Code"] = (
        df["Country Code"]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    # اكتشاف أعمدة السنوات
    year_columns = [
        col for col in df.columns
        if str(col).strip().replace(".0", "").isdigit()
        and 1900 <= int(float(str(col))) <= 2100
    ]

    # تحويل قيم السنوات إلى أرقام
    for col in year_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    raw_data[file.name] = df

    print("\n" + "=" * 65)
    print("File:", file.name)
    print("Shape after fixing headers:", df.shape)
    print("Columns:", df.columns.tolist()[:8], "...")
    print("Year range:", min(map(lambda x: int(float(x)), year_columns)),
          "to", max(map(lambda x: int(float(x)), year_columns)))
    print("Country-code duplicates:", df["Country Code"].duplicated().sum())
    print("Missing country codes:", df["Country Code"].isna().sum())

    print("\nMissing values in identifier columns:")
    print(
        df[["Country Name", "Country Code", "Indicator Name", "Indicator Code"]]
        .isna()
        .sum()
    )

    print("\nMost missing year columns (%):")
    missing_pct = df[year_columns].isna().mean().mul(100).sort_values(
        ascending=False
    )
    print(missing_pct.head(10).round(2))

    print("\nIndicator names:", df["Indicator Name"].dropna().unique())
    print("Indicator codes:", df["Indicator Code"].dropna().unique())

# مقارنة الأكواد الموجودة في الملفات بالقاموس
dictionary_codes = set(dictionary["ISO3"].dropna())

all_source_codes = set()

for df in raw_data.values():
    all_source_codes.update(df["Country Code"].dropna().tolist())

unmatched_codes = sorted(all_source_codes - dictionary_codes)

print("\n" + "=" * 65)
print("Unique source codes across all files:", len(all_source_codes))
print("Codes absent from dictionary:", len(unmatched_codes))
print(unmatched_codes)

Dictionary shape: (196, 13)
Duplicate ISO3 codes: 0
Missing ISO3 codes: 0

=================================================================
File: 01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls
Shape after fixing headers: (265, 70)
Columns: ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963'] ...
Year range: 1960 to 2025
Country-code duplicates: 0
Missing country codes: 0

Missing values in identifier columns:
Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
dtype: int64

Most missing year columns (%):
1960    100.0
1961    100.0
1962    100.0
1963    100.0
1964    100.0
1965    100.0
1966    100.0
1967    100.0
1968    100.0
1969    100.0
dtype: float64

Indicator names: ['GDP per capita, PPP (constant 2021 international $)']
Indicator codes: ['NY.GDP.PCAP.PP.KD']

=================================================================
File: 02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls
Shape after fixing headers: (265, 70)
Columns: ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963'] ...
Year range: 1960 to 2025
Country-code duplicates: 0
Missing country codes: 0

Missing values in identifier columns:
Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
dtype: int64

Most missing year columns (%):
1960    100.0
1961    100.0
1962    100.0
1963    100.0
1964    100.0
1965    100.0
1966    100.0
1967    100.0
1968    100.0
1969    100.0
dtype: float64

Indicator names: ['Literacy rate, adult total (% of people ages 15 and above)']
Indicator codes: ['SE.ADT.LITR.ZS']

=================================================================
File: 03_نسبة_الالتحاق_بالتعليم_الثانوي.xls
Shape after fixing headers: (265, 70)
Columns: ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1960', '1961', '1962', '1963'] ...
Year range: 1960 to 2025
Country-code duplicates: 0
Missing country codes: 0

Missing values in identifier columns:
Country Name      0
Country Code      0
Indicator Name    0
Indicator Code    0
dtype: int64

Most missing year columns (%):
1960    100.0
1961    100.0
1962    100.0
1963    100.0
1964    100.0
1965    100.0
1966    100.0
1967    100.0
1968    100.0
1969    100.0
dtype: float64

Indicator names: ['School enrollment, secondary (% gross)']
Indicator codes: ['SE.SEC.ENRR']

=================================================================
Unique source codes across all files: 265
Codes absent from dictionary: 71
['ABW', 'AFE', 'AFW', 'ARB', 'ASM', 'BMU', 'CEB', 'CHI', 'CSS', 'CUW', 'CYM', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'FRO', 'GIB', 'GRL', 'GUM', 'HIC', 'HKG', 'HPC', 'IBD', 'IBT', 'IDA', 'IDB', 'IDX', 'IMN', 'INX', 'LAC', 'LCN', 'LDC', 'LIC', 'LMC', 'LMY', 'LTE', 'MAC', 'MAF', 'MEA', 'MIC', 'MNA', 'MNP', 'NAC', 'NCL', 'OED', 'OSS', 'PRE', 'PRI', 'PSS', 'PST', 'PYF', 'SAS', 'SSA', 'SSF', 'SST', 'SXM', 'TCA', 'TEA', 'TEC', 'TLA', 'TMN', 'TSA', 'TSS', 'UMC', 'VGB', 'VIR', 'WLD', 'XKX']

In [7]:

# فحص جودة البيانات قبل التحويل والدمج
import pandas as pd

quality_results = []

for file_name, df in raw_data.items():

    year_columns = [
        col for col in df.columns
        if str(col).isdigit()
    ]

    values = df[year_columns]

    missing_count = int(values.isna().sum().sum())
    total_cells = int(values.size)
    non_missing_count = int(values.notna().sum().sum())

    print("\n" + "=" * 65)
    print("File:", file_name)
    print("Country/entity rows:", len(df))
    print("Year columns:", len(year_columns))
    print("Total year cells:", total_cells)
    print("Available values:", non_missing_count)
    print("Missing values:", missing_count)
    print("Missing percentage:", round(missing_count / total_cells * 100, 2), "%")

    # السنوات التي لا تحتوي على أي قيمة
    empty_years = values.columns[values.isna().all()].tolist()
    print("Completely empty years:", empty_years)

    # السنوات التي تحتوي على بيانات
    yearly_coverage = values.notna().sum()
    print("\nYears with the most available values:")
    print(yearly_coverage.sort_values(ascending=False).head(10))

    # فحص القيم السالبة
    negative_count = int((values < 0).sum().sum())
    print("\nNegative numeric values:", negative_count)

    # فحص النطاقات الخاصة بالمؤشرات
    if "01_" in file_name:
        print("GDP values below zero:", negative_count)

    elif "02_" in file_name:
        outside_range = ((values < 0) | (values > 100)).sum().sum()
        print("Literacy values outside 0-100:", int(outside_range))

    elif "03_" in file_name:
        below_zero = int((values < 0).sum().sum())
        print("Enrollment values below zero:", below_zero)
        print("Enrollment values above 100:",
              int((values > 100).sum().sum()))

    quality_results.append({
        "File": file_name,
        "Rows": len(df),
        "Years": len(year_columns),
        "Available_Values": non_missing_count,
        "Missing_Values": missing_count,
        "Missing_Pct": round(missing_count / total_cells * 100, 2),
        "Negative_Values": negative_count,
    })

quality_report = pd.DataFrame(quality_results)

print("\n\nFINAL QUALITY SUMMARY")
display(quality_report)

=================================================================
File: 01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls
Country/entity rows: 265
Year columns: 66
Total year cells: 17490
Available values: 8669
Missing values: 8821
Missing percentage: 50.43 %
Completely empty years: ['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989']

Years with the most available values:
2021    246
2022    246
2019    246
2018    246
2015    246
2014    246
2017    246
2020    246
2013    246
2016    246
dtype: int64

Negative numeric values: 0
GDP values below zero: 0

=================================================================
File: 02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls
Country/entity rows: 265
Year columns: 66
Total year cells: 17490
Available values: 2804
Missing values: 14686
Missing percentage: 83.97 %
Completely empty years: ['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1971', '1972', '2025']

Years with the most available values:
2019    94
2011    89
2018    87
2010    84
2015    84
2022    83
2017    82
2021    82
2016    82
2014    82
dtype: int64

Negative numeric values: 0
Literacy values outside 0-100: 0

=================================================================
File: 03_نسبة_الالتحاق_بالتعليم_الثانوي.xls
Country/entity rows: 265
Year columns: 66
Total year cells: 17490
Available values: 8307
Missing values: 9183
Missing percentage: 52.5 %
Completely empty years: ['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969']

Years with the most available values:
2011    201
2015    200
2005    198
2004    196
2012    195
2007    195
2014    194
2010    194
2021    193
2016    192
dtype: int64

Negative numeric values: 0
Enrollment values below zero: 0
Enrollment values above 100: 1255


FINAL QUALITY SUMMARY

,File,Rows,Years,Available_Values,Missing_Values,Missing_Pct,Negative_Values
0,01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls,265,66,8669,8821,50.43,0
1,02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls,265,66,2804,14686,83.97,0
2,03_نسبة_الالتحاق_بالتعليم_الثانوي.xls,265,66,8307,9183,52.50,0

In [8]:

# مراجعة الأكواد قبل توحيد الدول
import pandas as pd

dictionary_codes = set(
    dictionary["ISO3"].dropna().str.strip().str.upper()
)

code_audit = []

for file_name, df in raw_data.items():
    source_codes = set(
        df["Country Code"].dropna().str.strip().str.upper()
    )

    unmatched = sorted(source_codes - dictionary_codes)

    code_audit.append({
        "File": file_name,
        "Unique_Source_Codes": len(source_codes),
        "Codes_In_Dictionary": len(source_codes & dictionary_codes),
        "Codes_Not_In_Dictionary": len(unmatched),
        "Unmatched_Codes": ", ".join(unmatched)
    })

code_audit_df = pd.DataFrame(code_audit)

display(code_audit_df)

# عرض الأكواد غير المطابقة مرة واحدة
all_source_codes = set()

for df in raw_data.values():
    all_source_codes.update(
        df["Country Code"].dropna().str.strip().str.upper()
    )

unmatched_codes = sorted(all_source_codes - dictionary_codes)

print("Total unmatched codes:", len(unmatched_codes))
print(unmatched_codes)

# فحص أعمدة القاموس المتعلقة بتصنيف الدول
display(
    dictionary[
        ["ISO3", "Country", "WB_Name", "Region", "Income_Group"]
    ].head(10)
)

,File,Unique_Source_Codes,Codes_In_Dictionary,Codes_Not_In_Dictionary,Unmatched_Codes
0,01_الناتج_المحلي_للفرد_بالقوة_الشرائية.xls,265,194,71,"ABW, AFE, AFW, ARB, ASM, BMU, CEB, CHI, CSS, C..."
1,02_معدل_معرفة_القراءة_والكتابة_للبالغين.xls,265,194,71,"ABW, AFE, AFW, ARB, ASM, BMU, CEB, CHI, CSS, C..."
2,03_نسبة_الالتحاق_بالتعليم_الثانوي.xls,265,194,71,"ABW, AFE, AFW, ARB, ASM, BMU, CEB, CHI, CSS, C..."

Total unmatched codes: 71
['ABW', 'AFE', 'AFW', 'ARB', 'ASM', 'BMU', 'CEB', 'CHI', 'CSS', 'CUW', 'CYM', 'EAP', 'EAR', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'FRO', 'GIB', 'GRL', 'GUM', 'HIC', 'HKG', 'HPC', 'IBD', 'IBT', 'IDA', 'IDB', 'IDX', 'IMN', 'INX', 'LAC', 'LCN', 'LDC', 'LIC', 'LMC', 'LMY', 'LTE', 'MAC', 'MAF', 'MEA', 'MIC', 'MNA', 'MNP', 'NAC', 'NCL', 'OED', 'OSS', 'PRE', 'PRI', 'PSS', 'PST', 'PYF', 'SAS', 'SSA', 'SSF', 'SST', 'SXM', 'TCA', 'TEA', 'TEC', 'TLA', 'TMN', 'TSA', 'TSS', 'UMC', 'VGB', 'VIR', 'WLD', 'XKX']

  ISO3               Country               WB_Name Region  Income_Group
0  AFG           Afghanistan           Afghanistan    EMR           Low
1  AGO                Angola                Angola    AFR  Lower-middle
2  ALB               Albania               Albania    EUR  Upper-middle
3  AND               Andorra               Andorra    EUR          High
4  ARE  United Arab Emirates  United Arab Emirates    EMR          High
5  ARG             Argentina             Argentina    AMR  Upper-middle
6  ARM               Armenia               Armenia    EUR  Upper-middle
7  ATG   Antigua and Barbuda   Antigua and Barbuda    AMR          High
8  AUS             Australia             Australia    WPR          High
9  AUT               Austria               Austria    EUR          High

In [9]:

from pathlib import Path
import pandas as pd

# ==========================================
# 1. إعداد الملفات والأسماء النهائية
# ==========================================

output_dir = Path.cwd()

dictionary_file = output_dir / "country_dictionary_v1.csv"

output_csv = output_dir / "socioeconomic_education_clean.csv"
output_log = output_dir / "cleaning_log.txt"
unmatched_csv = output_dir / "unmatched_codes_review.csv"

dictionary = pd.read_csv(
    dictionary_file,
    dtype={"ISO3": "string"}
)

dictionary["ISO3"] = (
    dictionary["ISO3"].str.strip().str.upper()
)

dictionary["Country"] = dictionary["Country"].str.strip()

if dictionary["ISO3"].isna().any():
    raise ValueError("Dictionary contains missing ISO3 codes.")

if dictionary["ISO3"].duplicated().any():
    raise ValueError("Dictionary contains duplicate ISO3 codes.")

# نحتفظ فقط بأعمدة القاموس المطلوبة في الناتج
country_lookup = dictionary[["ISO3", "Country"]].copy()

# ==========================================
# 2. تحديد أسماء المؤشرات
# ==========================================

indicator_mapping = {
    "01_": "GDP_Per_Capita_PPP_2021",
    "02_": "Adult_Literacy_Rate",
    "03_": "Secondary_Enrollment_Gross_Pct",
}

expected_columns = [
    "GDP_Per_Capita_PPP_2021",
    "Secondary_Enrollment_Gross_Pct",
    "Adult_Literacy_Rate",
]

dictionary_codes = set(country_lookup["ISO3"])

cleaned_long = {}
source_stats = []
log_lines = []

log_lines.append("DATA CLEANING LOG")
log_lines.append("=" * 60)
log_lines.append(f"Dictionary rows: {len(dictionary)}")
log_lines.append(
    f"Unique dictionary ISO3 codes: {dictionary['ISO3'].nunique()}"
)

# ==========================================
# 3. فحص الأكواد وتحويل كل ملف إلى Long Format
# ==========================================

for file_name, df_original in raw_data.items():

    df = df_original.copy()

    # تحديد اسم العمود النهائي من اسم الملف
    prefix = next(
        (p for p in indicator_mapping if file_name.startswith(p)),
        None
    )

    if prefix is None:
        raise ValueError(f"Unknown indicator file: {file_name}")

    indicator_column = indicator_mapping[prefix]

    year_columns = [
        col for col in df.columns
        if str(col).isdigit()
    ]

    if not year_columns:
        raise ValueError(f"No year columns found in {file_name}")

    df["Country Code"] = (
        df["Country Code"]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    # التأكد من عدم تكرار كود الدولة في الملف
    if df["Country Code"].duplicated().any():
        raise ValueError(f"Duplicate country codes in {file_name}")

    # تسجيل الأكواد غير الموجودة في القاموس
    source_codes = set(df["Country Code"].dropna())
    unmatched = sorted(source_codes - dictionary_codes)

    log_lines.append("")
    log_lines.append(f"Source file: {file_name}")
    log_lines.append(f"Source rows: {len(df)}")
    log_lines.append(f"Year columns: {len(year_columns)}")
    log_lines.append(f"Unmatched codes: {len(unmatched)}")
    log_lines.append(f"Unmatched code list: {', '.join(unmatched)}")

    # تحويل قيم السنوات إلى أرقام
    for col in year_columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    # الأكواد غير المطابقة تُسجل للمراجعة، ولا تُدمج
    matched_df = df[df["Country Code"].isin(dictionary_codes)].copy()

    # الاحتفاظ بالحقول اللازمة فقط
    matched_df = matched_df[
        ["Country Code"] + year_columns
    ]

    # Wide -> Long
    long_df = matched_df.melt(
        id_vars=["Country Code"],
        value_vars=year_columns,
        var_name="Year",
        value_name=indicator_column
    )

    long_df = long_df.rename(columns={"Country Code": "ISO3"})

    long_df["ISO3"] = long_df["ISO3"].astype("string")
    long_df["Year"] = pd.to_numeric(
        long_df["Year"], errors="raise"
    ).astype("int64")

    # التحقق من المفتاح قبل الدمج
    if long_df.duplicated(["ISO3", "Year"]).any():
        raise ValueError(
            f"Duplicate ISO3 + Year keys in {file_name}"
        )

    # فحص نطاقات المؤشرات: إيقاف التنفيذ عند وجود قيم غير صالحة
    if indicator_column == "GDP_Per_Capita_PPP_2021":
        invalid = long_df[indicator_column] < 0

    elif indicator_column == "Adult_Literacy_Rate":
        invalid = (
            (long_df[indicator_column] < 0)
            | (long_df[indicator_column] > 100)
        )

    else:
        # Gross enrollment may exceed 100%, but cannot be negative.
        invalid = long_df[indicator_column] < 0

    invalid_count = int(invalid.fillna(False).sum())

    log_lines.append(
        f"Invalid values in {indicator_column}: {invalid_count}"
    )

    if invalid_count:
        raise ValueError(
            f"Invalid values found in {indicator_column}. "
            "Review them before continuing."
        )

    cleaned_long[indicator_column] = long_df

    source_stats.append({
        "Indicator": indicator_column,
        "Source_Rows": len(df),
        "Matched_Codes": matched_df["Country Code"].nunique(),
        "Long_Rows": len(long_df),
        "Available_Values": int(long_df[indicator_column].notna().sum()),
        "Missing_Values": int(long_df[indicator_column].isna().sum()),
    })

# ==========================================
# 4. حفظ قائمة الأكواد غير المطابقة للمراجعة
# ==========================================

all_source_codes = set()

for df in raw_data.values():
    all_source_codes.update(
        df["Country Code"].dropna().str.strip().str.upper()
    )

all_unmatched_codes = sorted(all_source_codes - dictionary_codes)

unmatched_review = pd.DataFrame({
    "Unmatched_Code": all_unmatched_codes
})

unmatched_review.to_csv(
    unmatched_csv,
    index=False,
    encoding="utf-8-sig"
)

log_lines.append("")
log_lines.append(
    f"Total unique unmatched codes excluded from final dataset: "
    f"{len(all_unmatched_codes)}"
)
log_lines.append(
    f"Review file: {unmatched_csv.name}"
)

# ==========================================
# 5. دمج المؤشرات باستخدام ISO3 + Year
# ==========================================

merged_df = None

for indicator_column in [
    "GDP_Per_Capita_PPP_2021",
    "Secondary_Enrollment_Gross_Pct",
    "Adult_Literacy_Rate",
]:

    current_df = cleaned_long[indicator_column]

    if merged_df is None:
        merged_df = current_df.copy()
    else:
        rows_before = len(merged_df)

        merged_df = merged_df.merge(
            current_df,
            on=["ISO3", "Year"],
            how="outer",
            validate="one_to_one"
        )

        log_lines.append(
            f"Merging {indicator_column}: "
            f"rows before={rows_before}, rows after={len(merged_df)}"
        )

# إضافة اسم الدولة من القاموس
merged_df = merged_df.merge(
    country_lookup,
    on="ISO3",
    how="left",
    validate="many_to_one"
)

if merged_df["Country"].isna().any():
    raise ValueError("Some final rows have no country name.")

# ==========================================
# 6. التحقق من البيانات النهائية
# ==========================================

key_columns = ["ISO3", "Year"]

if merged_df.duplicated(key_columns).any():
    raise ValueError("Duplicate ISO3 + Year keys after merge.")

# عدد الصفوف قبل حذف الصفوف التي كل مؤشراتها Missing
rows_before_empty_removal = len(merged_df)

# حذف الصفوف التي لا تحتوي على أي مؤشر متاح
merged_df = merged_df.dropna(
    subset=expected_columns,
    how="all"
).copy()

# ترتيب الأعمدة
final_columns = [
    "ISO3",
    "Country",
    "Year",
    "GDP_Per_Capita_PPP_2021",
    "Secondary_Enrollment_Gross_Pct",
    "Adult_Literacy_Rate",
]

merged_df = merged_df[final_columns].sort_values(
    ["ISO3", "Year"]
).reset_index(drop=True)

# إعادة فحص المفتاح بعد الحذف والترتيب
if merged_df.duplicated(["ISO3", "Year"]).any():
    raise ValueError("Final dataset contains duplicate keys.")

if merged_df[expected_columns].isna().all(axis=1).any():
    raise ValueError("Rows with all indicators missing remain.")

# ==========================================
# 7. تقرير التغطية النهائية
# ==========================================

print("SOURCE SUMMARY")
source_summary = pd.DataFrame(source_stats)
display(source_summary)

print("\nFINAL DATASET")
print("Rows:", len(merged_df))
print("Unique countries:", merged_df["ISO3"].nunique())
print("Year range:", merged_df["Year"].min(), "-", merged_df["Year"].max())
print("Duplicate ISO3 + Year:", merged_df.duplicated(["ISO3", "Year"]).sum())
print("Rows removed because all indicators were missing:",
      rows_before_empty_removal - len(merged_df))

coverage_rows = []

for col in expected_columns:
    available = int(merged_df[col].notna().sum())
    missing = int(merged_df[col].isna().sum())
    total = len(merged_df)

    coverage_rows.append({
        "Indicator": col,
        "Available_Values": available,
        "Missing_Values": missing,
        "Missing_Pct": round(missing / total * 100, 2) if total else 0,
        "Coverage_Pct": round(available / total * 100, 2) if total else 0,
    })

coverage_report = pd.DataFrame(coverage_rows)
display(coverage_report)

# ==========================================
# 8. حفظ الناتج وسجل التنظيف
# ==========================================

merged_df.to_csv(
    output_csv,
    index=False,
    encoding="utf-8-sig"
)

log_lines.extend([
    "",
    "FINAL DATASET SUMMARY",
    f"Final rows: {len(merged_df)}",
    f"Final unique countries: {merged_df['ISO3'].nunique()}",
    f"Year range: {merged_df['Year'].min()} - {merged_df['Year'].max()}",
    f"Rows before removing all-missing records: {rows_before_empty_removal}",
    f"Rows removed because all indicators were missing: "
    f"{rows_before_empty_removal - len(merged_df)}",
    f"Final duplicate ISO3 + Year keys: "
    f"{merged_df.duplicated(['ISO3', 'Year']).sum()}",
    "",
    "INDICATOR COVERAGE",
])

for _, row in coverage_report.iterrows():
    log_lines.append(
        f"{row['Indicator']}: "
        f"available={row['Available_Values']}, "
        f"missing={row['Missing_Values']}, "
        f"missing_pct={row['Missing_Pct']}%, "
        f"coverage_pct={row['Coverage_Pct']}%"
    )

log_lines.extend([
    "",
    "Missing values were not imputed.",
    "No interpolation, forward fill, or backward fill was applied.",
    "Gross secondary enrollment values above 100% were retained.",
    "Source codes absent from the country dictionary were excluded "
    "from the final dataset and recorded for review.",
])

output_log.write_text("\n".join(log_lines), encoding="utf-8")

print("\nSAVED FILES")
print(output_csv)
print(output_log)
print(unmatched_csv)

print("\nPreview of final dataset:")
display(merged_df.head(10))

SOURCE SUMMARY

,Indicator,Source_Rows,Matched_Codes,Long_Rows,Available_Values,Missing_Values
0,GDP_Per_Capita_PPP_2021,265,194,12804,6630,6174
1,Adult_Literacy_Rate,265,194,12804,1102,11702
2,Secondary_Enrollment_Gross_Pct,265,194,12804,6023,6781

FINAL DATASET
Rows: 8634
Unique countries: 194
Year range: 1970 - 2025
Duplicate ISO3 + Year: 0
Rows removed because all indicators were missing: 4170

,Indicator,Available_Values,Missing_Values,Missing_Pct,Coverage_Pct
0,GDP_Per_Capita_PPP_2021,6630,2004,23.21,76.79
1,Secondary_Enrollment_Gross_Pct,6023,2611,30.24,69.76
2,Adult_Literacy_Rate,1102,7532,87.24,12.76

SAVED FILES
e:\Task2 Data Analysis\socioeconomic_education_clean.csv
e:\Task2 Data Analysis\cleaning_log.txt
e:\Task2 Data Analysis\unmatched_codes_review.csv

Preview of final dataset:

,ISO3,Country,Year,GDP_Per_Capita_PPP_2021,Secondary_Enrollment_Gross_Pct,Adult_Literacy_Rate
0,AFG,Afghanistan,1970,NaN,8.36410,NaN
1,AFG,Afghanistan,1971,NaN,9.37827,NaN
2,AFG,Afghanistan,1972,NaN,10.41424,NaN
3,AFG,Afghanistan,1973,NaN,10.93218,NaN
4,AFG,Afghanistan,1974,NaN,11.09488,NaN
5,AFG,Afghanistan,1975,NaN,11.59559,NaN
6,AFG,Afghanistan,1976,NaN,12.45826,NaN
7,AFG,Afghanistan,1977,NaN,13.25927,NaN
8,AFG,Afghanistan,1978,NaN,13.82134,NaN
9,AFG,Afghanistan,1979,NaN,NaN,18.16

In [10]:
# Final validation checks

final_df = pd.read_csv("socioeconomic_education_clean.csv")

indicator_cols = [
    "GDP_Per_Capita_PPP_2021",
    "Secondary_Enrollment_Gross_Pct",
    "Adult_Literacy_Rate"
]

assert list(final_df.columns) == [
    "ISO3",
    "Country",
    "Year",
    "GDP_Per_Capita_PPP_2021",
    "Secondary_Enrollment_Gross_Pct",
    "Adult_Literacy_Rate"
]

assert not final_df.duplicated(["ISO3", "Year"]).any()
assert final_df["ISO3"].notna().all()
assert final_df["Country"].notna().all()
assert final_df["Year"].notna().all()
assert final_df[indicator_cols].notna().any(axis=1).all()

assert (final_df["GDP_Per_Capita_PPP_2021"].dropna() >= 0).all()
assert final_df["Adult_Literacy_Rate"].dropna().between(0, 100).all()

print("All final validation checks passed.")
print("Rows:", len(final_df))
print("Countries:", final_df["ISO3"].nunique())
print("Years:", final_df["Year"].min(), "-", final_df["Year"].max())

All final validation checks passed.
Rows: 8634
Countries: 194
Years: 1970 - 2025

In [11]:
indicator_cols = [
    "GDP_Per_Capita_PPP_2021",
    "Secondary_Enrollment_Gross_Pct",
    "Adult_Literacy_Rate"
]

coverage_rows = []

for col in indicator_cols:
    available = final_df[final_df[col].notna()]

    coverage_rows.append({
        "Indicator": col,
        "Available_Country_Year_Rows": len(available),
        "Countries_With_Data": available["ISO3"].nunique(),
        "Years_With_Data": available["Year"].nunique(),
        "First_Year_With_Data": (
            available["Year"].min() if not available.empty else None
        ),
        "Last_Year_With_Data": (
            available["Year"].max() if not available.empty else None
        ),
        "Missing_Values": final_df[col].isna().sum()
    })

coverage_summary = pd.DataFrame(coverage_rows)
display(coverage_summary)

,Indicator,Available_Country_Year_Rows,Countries_With_Data,Years_With_Data,First_Year_With_Data,Last_Year_With_Data,Missing_Values
0,GDP_Per_Capita_PPP_2021,6630,186,36,1990,2025,2004
1,Secondary_Enrollment_Gross_Pct,6023,193,56,1970,2025,2611
2,Adult_Literacy_Rate,1102,163,51,1970,2024,7532